version: "3"

services:
  redis:
    hostname: redis_service
    image: redis:7.0.4
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - ${PWD}/devOps/volume/redis:/data